### ISSUE TITLE
Different cases of misspelt words which are not highlighted

### ISSUE THREAD

**Issue by tonygoldcrest** [kmszk/CCSpellCheck.vim#2] opened 2018-11-03 17:52 UTC
Hello,

Thank you for the great plugin!
1. I noticed that the plugin doesn't highlight misspelt lowercase words:
![image](https://user-images.githubusercontent.com/5630034/47955345-6f020e80-df9f-11e8-8b03-f0b21d9d293e.png)

It would be nice to have misspelt lowercase words highlighting since if you enable standard vim's `set spell` to do that, it destroys all the features of this plugin.

2. Also I noticed that misspellings are not highlighted when there is only one letter in the "camel-case" part:
![image](https://user-images.githubusercontent.com/5630034/47955466-2f3c2680-dfa1-11e8-8241-f31c04d91568.png)

3. And finally it would be really cool to have uppercase words covered as well:
![image](https://user-images.githubusercontent.com/5630034/47955481-6a3e5a00-dfa1-11e8-884e-47c9e26677d2.png)

I know that the plugin is camel-case specific, but it works really great and I would really like to use it instead of the standard spell checking. Please, consider my notes to make it even better.

**Comment by kamykn** [comment] 2018-11-05 04:49
Thank you for your reporting👍
I'm trying to find out about cause this problem.
Please wait for a while until I fix it...!

**Comment by kamykn** [comment] 2018-11-06 15:58
@peancored 
Hi, 
Maybe the issue is resolved with b248ece.
Could you please check if it is fixed in newer versions?

**Comment by tonygoldcrest** [comment] 2018-11-06 20:50
Hi @kamykn,
Thank you very much!

The 2) is fixed!
![image](https://user-images.githubusercontent.com/5630034/48092338-0d4ada00-e215-11e8-9534-1d12c6ae1bda.png)

But 1) and 3) remain:
![image](https://user-images.githubusercontent.com/5630034/48092371-281d4e80-e215-11e8-9962-a705f1f90b06.png)

I noticed a funny behaviour though:
Whenever 1) and 3) are not highlighted and I use some camelcase with the same wrong spelling anywhere, it starts highlighting:
![image](https://user-images.githubusercontent.com/5630034/48092450-6450af00-e215-11e8-812b-27fde0bff15e.png)

Hope it helps!

P.S. I think if it will be fixed the plugin could be renamed to something like "Improved Vim Spelling" easily, as it will solve all the issues that standard spell checker has! 

EDIT:
Noticed one more case:
![image](https://user-images.githubusercontent.com/5630034/48093010-d970b400-e216-11e8-96c8-9f3e0a28696d.png)

**Comment by tonygoldcrest** [comment] 2018-11-06 21:13
Hi @kamykn,

I may be wrong because I'm not familiar with VimScript at all, but `l:spellBadList` seems to contain only camel case words here:
https://github.com/kamykn/CCSpellCheck.vim/blob/337ae67ad497e57d86e8759b5398b18ff53a5d4d/autoload/CCSpellCheck.vim#L212
because of this function implementation:
https://github.com/kamykn/CCSpellCheck.vim/blob/337ae67ad497e57d86e8759b5398b18ff53a5d4d/autoload/CCSpellCheck.vim#L11

Hope it helps anyhow.

**Comment by kamykn** [comment] 2018-11-07 04:57
@peancored 
> l:spellBadList seems to contain only camel case words here:

Yes, this list contain only camelcase words. But, I noticed you not only want more highlighted words, but also spell checking target words.

> Improved Vim Spelling

That's a nice idea.
It means that this plugin should also target non camelcase.
I noticed that it would be better to do so.
Thank you.

I try to fix it.

**Comment by kamykn** [comment] 2018-11-23 01:26
@peancored
I made a new plugin 😆!
https://github.com/kamykn/spelunker.vim

I hope you like it!

**Comment by tonygoldcrest** [comment] 2018-11-23 08:24
@kamykn That looks awesome!! I'll check it out asap!
Thank you very much 🎉

**Comment by tonygoldcrest** [comment] 2018-11-23 08:26
@kamykn I recommend you post it to https://www.reddit.com/r/vim/ so that people know about such an awesome plugin!

**Closed as completed** 2019-06-27 09:09 UTC
